version: '2'
services:
  # using pipeline/influx
  # nxos-pipeline:
  #   build: nxos-pipeline
  #   ports:
  #     - 57500:57500
  #   volumes:
  #     - ./nxos-pipeline/config:/etc/pipeline
  #   links:
  #     - "elasticsearch:elasticsearch"
  #     - "prometheus:prometheus"
  #   depends_on:
  #     - elasticsearch
  #     - prometheus

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
  #   ports:
  #     - 9200:9200
  #     - 9300:9300

  # using elk stack

  # receiver:
  #   image: dockercisco/telemetryreceiver
  #   ports:
  #     - 57500:57500
  #   command: "/grpc/telemetry/src/telemetry_receiver 57500 elk 9200 1"
  #   links:
  #     - "elk:elk"
  #   depends_on:
  #     - elk
  #
  # elk:
  #   image: dockercisco/elklat
  #   volumes:
  #     - ./elk:/elk
  #   ports:
  #     - 9200:9200
  #     - 5601:5601
  #   command: /usr/local/bin/start.sh


  iosxr-pipeline:
    build: iosxr-pipeline
    ports:
      - 5432:5432
    command: "./startup.sh"
    links:
      - "influxdb:influxdb"
      - "prometheus:promethus"
    volumes:
      - ./iosxr-pipeline/data:/data
      - ./iosxr-pipeline/config:/etc/pipeline
    depends_on:
      - influxdb
      - prometheus
    environment:
      - influx_ip=influxdb
      - influx_port=8086



  influxdb:
    image: influxdb:1.1.3
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
    ports:
      - "8086:8086"
      - "8083:8083"

  prometheus:
    image: prom/prometheus:v1.5.2
    volumes:
      - ./prometheus:/etc/prometheus
    command: "-config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:master
    volumes:
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/datasources:/etc/grafana/datasources
    ports:
      - "3000:3000"
    environment:
     - "GF_LOG_LEVEL=debug"
     - "GF_LOG_FILTERS=alerting.notifier.webhook:debug"
     - "GF_AUTH_ANONYMOUS_ENABLED=true"
     - "GF_DASHBOARDS_JSON_ENABLED=true"
     - "GF_DASHBOARDS_JSON_PATH=/etc/grafana/dashboards/"
     - "GF_PATHS_DATASOURCES=/etc/grafana/datasources/"
     - "GF_PATHS_PROVISIONING=/etc/grafana/"
    links:
      - "influxdb:influxdb"
      - "prometheus:prometheus"
    depends_on:
      - influxdb
      - prometheus
