{
 "title": "Device Health",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": "SHOW TAG VALUES FROM \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters\" WITH KEY=\"Producer\"\t\t\t"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
     "select": [
      [
       { "params": [ "total-cpu-one-minute" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "$Device" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary",
     "query": "SELECT (last(\"system-ram-memory\") - last(\"free-application-memory\")) * 100 / last(\"system-ram-memory\") FROM \"Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary\" WHERE \"Producer\" =~ /^$Device$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "free-physical-memory" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "$Device" }
     ]
    }
   ]
  },
  {
   "title": "OSPF Neighbors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-ipv4-ospf-oper:ospf/processes/process/default-vrf/ospf-summary",
     "select": [
      [
       { "params": [ "sa-num-nbrs-up" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "OSPF Routes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-ip-rib-ipv4-oper:rib/rib-table-ids/rib-table-id/summary-protos/summary-proto",
     "query": "SELECT \"proto-route-count__active-routes-count\" FROM \"autogen\".\"Cisco-IOS-XR-ip-rib-ipv4-oper:rib/rib-table-ids/rib-table-id/summary-protos/summary-proto\" WHERE (\"name\" = 'ospf') AND $timeFilter",
     "select": [
      [
       {
        "params": [
         "proto-route-count__active-routes-count"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "ospf" }
     ]
    }
   ]
  },
  {
   "title": "BGP Peers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-active/default-vrf/process-info",
     "select": [
      [
       {
        "params": [
         "global__established-neighbors-count-total"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "$Device" }
     ]
    }
   ]
  },
  {
   "title": "BGP Prefix Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-active/default-vrf/process-info",
     "query": "SELECT \"proto-route-count__active-routes-count\" FROM \"autogen\".\"Cisco-IOS-XR-ip-rib-ipv4-oper:rib/rib-table-ids/rib-table-id/summary-protos/summary-proto\" WHERE (\"Producer\" = '$Device') AND $timeFilter",
     "select": [
      [
       { "params": [ "vrf__path-count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "$Device" },
      { "condition": "AND", "key": "vrf-name", "operator": "=", "value": "default" }
     ]
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "[[tag_interface-name]]",
     "groupBy": [
      { "params": [ "interface-name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "bytes-received" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "$Device" }
     ]
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "[[tag_interface-name]]",
     "groupBy": [
      { "params": [ "interface-name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "bytes-received" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "$Device" }
     ]
    }
   ]
  },
  {
   "title": "Packets Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_interface-name]]",
     "groupBy": [
      { "params": [ "interface-name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "packets-received" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "$Device" }
     ]
    }
   ]
  },
  {
   "title": "Packets Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_interface-name]]",
     "groupBy": [
      { "params": [ "interface-name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "packets-sent" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "$Device" }
     ]
    }
   ]
  }
 ]
}