{
 "title": "WAN Overview",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "OSPF Neighbor Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_Producer]]",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ipv4-ospf-oper:ospf/processes/process/default-vrf/ospf-summary",
     "select": [
      [
       { "params": [ "sa-num-nbrs-up" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_Producer]]",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
     "select": [
      [
       { "params": [ "total-cpu-one-minute" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "OSPF Routes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_Producer",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-ip-rib-ipv4-oper:rib/rib-table-ids/rib-table-id/summary-protos/summary-proto",
     "select": [
      [
       {
        "params": [
         "proto-route-count__active-routes-count"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "ospf" }
     ]
    }
   ]
  },
  {
   "title": "WAN Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_Producer - [[tag_interface-name]]",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" },
      { "params": [ "interface-name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "query": "SELECT non_negative_derivative(last(\"bytes-received\"), 1s) *8 FROM \"Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters\" WHERE $timeFilter GROUP BY time($interval), \"interface-name\" fill(null)",
     "select": [
      [
       { "params": [ "bytes-sent" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}